name: Test Dispatch
on:
  repository_dispatch:
    # can be multiple types to dispatch ...
    types: [do-something]
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Start test
        run: echo Test is running
      - name: Payload check
        run: 'echo "Payload from message: ${{ github.event.client_payload.runtest }}"'
      - name: Do something conditional
        if: github.event.client_payload.runtest == true
        run: ./github/runtest.sh
