name: Test Dispatch
on:
  repository_dispatch:
jobs:
  build:
    name: Test Remote Dispatch Functionality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check Dependency Versions
        if: github.event.client_payload.runtest == true
        run: ./runtest.sh
