name: Test Dispatch
on:
  repository_dispatch:
    types: deploy
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Deploy to GitHub Pages
        with:
          REMOTE_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: yurikoval/middleman-gh-pages-action@master
